name: adiza_exchange
description: A contact exchange application written in flutter.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  stacked: ^2.3.15
  stacked_services: ^0.9.4
  qr_code_scanner: ^1.0.0
  phosphor_flutter: ^1.4.0
  qr_flutter: ^4.0.0
  image_picker: ^0.8.5+3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner:
  stacked_generator:

flutter:
  uses-material-design: true

  assets:

    - assets/logo_red/logo_red.png
    - assets/logo_red/0.75x/logo_red.png
    - assets/logo_red/1.0x/logo_red.png
    - assets/logo_red/1.5x/logo_red.png
    - assets/logo_red/2.0x/logo_red.png
    - assets/logo_red/3.0x/logo_red.png
    - assets/logo_red/4.0x/logo_red.png

    - assets/walkthrough/walkthrough.png
    - assets/walkthrough/0.75x/walkthrough.png
    - assets/walkthrough/1.0x/walkthrough.png
    - assets/walkthrough/1.5x/walkthrough.png
    - assets/walkthrough/2.0x/walkthrough.png
    - assets/walkthrough/3.0x/walkthrough.png
    - assets/walkthrough/4.0x/walkthrough.png

    - assets/sign_in_photo/sign_in_photo.png
    - assets/sign_in_photo/0.75x/sign_in_photo.png
    - assets/sign_in_photo/1.0x/sign_in_photo.png
    - assets/sign_in_photo/1.5x/sign_in_photo.png
    - assets/sign_in_photo/2.0x/sign_in_photo.png
    - assets/sign_in_photo/3.0x/sign_in_photo.png
    - assets/sign_in_photo/4.0x/sign_in_photo.png

    - assets/image/image.png
    - assets/image/0.75x/image.png
    - assets/image/1.0x/image.png
    - assets/image/1.5x/image.png
    - assets/image/2.0x/image.png
    - assets/image/3.0x/image.png
    - assets/image/4.0x/image.png

    - assets/joan/joan.png
    - assets/joan/0.75x/joan.png
    - assets/joan/1.0x/joan.png
    - assets/joan/1.5x/joan.png
    - assets/joan/2.0x/joan.png
    - assets/joan/3.0x/joan.png
    - assets/joan/4.0x/joan.png

    - assets/larry/larry.png

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
